### ISSUE TITLE
-x360 is missing in vbsp

### ISSUE THREAD

**Issue by metalex10** [Revenge282/SlimBSP#1]
this,-x360 is missing in vbsp
is you implemented -x360 command?

**Comment by AusHick** [comment]
I have not implemented any support for Xbox 360.  The base Source SDK 2013 also seems to be lacking what you are looking for:

https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/utils/vbsp/vbsp.cpp#L1106

Unfortunately, this repo is focused mainly on PC and Garry's Mod, so I'm not going to be looking into supporting this.  Sorry.
